spring:
  application:
    name: iboi
  datasource:
    url: jdbc:h2:mem:iboi-db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    jwt:
      secret: pQlRYusEJ7XfrRmFbjNVEVqymMZzbMLqzvCBvh7OrMU=
      expiration: 43200000

asaas:
  enabled: false
  base-url: https://api-sandbox.asaas.com
  api-key: ""
  webhook-token: ""
  user-agent: iboi-billing

app:
  seed:
    enabled : true
#    enabled: ${APP_SEED_ENABLED:false}
