package com.iboi.ia.domain

enum class TipoAlerta {
    VACINA_ATRASADA,
    PESO_ABAIXO_MEDIA,
    SEM_PESAGEM_RECENTE,
    MORTALIDADE_ALTA,
    CUSTO_ELEVADO,
    GANHO_PESO_BAIXO,
    ANIMAL_RISCO_SANITARIO,
    RECOMENDACAO_DESMAME,
    RECOMENDACAO_VENDA,
    RECOMENDACAO_TRATAMENTO
}
